name: Deploy Stack

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Staging server
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rlgoDzvc -i"
        REMOTE_HOST: ${{ secrets.DEPLOY_REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.DEPLOY_REMOTE_USER }}
        SOURCE: "./"
        TARGET: poga-deploy
        # SCRIPT_BEFORE: |
        #   mkdir -p poga-deploy && echo -e ${{ vars.SETTINGS }} > ./poga-deploy/stacks/.env
        # SCRIPT_AFTER: |
        #   whoami
        #   ls -al
        #   echo $RSYNC_STDOUT